spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  kafka:
    bootstrap-servers: kafka:9092

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/auth_db
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    baseline-on-migrate: true
    placeholders:
      flyway.skipDatabaseTypeCheck: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:change-me}
  expiration: 3600000
  refresh-expiration: 604800000
